import type { Metadata } from "next";
import "./globals.css";
import ChatWidget from "../components/chatbot/ChatWidget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}
        <ChatWidget />
      </body>
    </html>
  );
}
