import "./globals.css";
import Chatbot from "../components/Chatbot/Chatbot";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        {/* Chatbot mounted on every page (right-bottom) */}
        <Chatbot />
      </body>
    </html>
  );
}

